### ISSUE TITLE
Cannot add more contracts to MihaiDejeu/self-QA repository

### ISSUE THREAD

**Issue by MihaiDejeu** [self-xdsd/self-web#268] opened 2020-12-15 20:45 UTC
![image](https://user-images.githubusercontent.com/75386651/102270888-3cb98e00-3f27-11eb-9919-384757d1f91a.png)

**Comment by charlesmike** [comment] 2020-12-15 20:45
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-25T22:45:56.893033``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment] 2020-12-15 20:46
@MihaiDejeu please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by charlesmike** [comment] 2020-12-19 22:00
@amihaiemil Don't forget to close this ticket before the deadline (2020-12-25T22:45:56). You are past the first half of the allowed period.

**Comment by charlesmike** [comment] 2020-12-25 20:47
@amihaiemil Looks like you've missed the task deadline (2020-12-25T22:45:56). You are now resigned from this task.

Please stop working on it, you will not be paid. I will assign it to someone else soon.

**Comment by charlesmike** [comment] 2020-12-25 20:48
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-04T22:48:06.592675``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment] 2020-12-29 22:03
@criske Don't forget to close this ticket before the deadline (2021-01-04T22:48:06). You are past the first half of the allowed period.

**Comment by criske** [comment] 2020-12-30 14:09
@MihaiDejeu @amihaiemil Couldn't replicate it.  It looks like a transaction error?  Was this an one time error or you coudn't add new contracts anymore?
Unfortunately db erros are suppressed by `self-storage` with more or less meaningful  `IlegalStateException`  messages to prevent sensitive data to be leaked.

**Comment by amihaiemil** [comment] 2020-12-31 08:38
@criske I also could not reproduce it. My best guess is that his session expired :D 
Let's close this for now.

**Closed by amihaiemil** 2020-12-31 08:38 UTC
Labels: @criske, bug, web

**Comment by charlesmike** [comment] 2020-12-31 08:39
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
